# This file is a template, and might need editing before it works on your project.
---
stages:
  - build_report

variables:
  # Feel free to choose the image that suits you best.
  # blang/latex:latest ... Former image used in this template. No longer maintained by author.
  # listx/texlive:2020 ... The default, referring to TexLive 2020. Current at least to 2021-02-02.

  # Additional alternatives with high Docker pull counts:
  # thomasweise/docker-texlive-full
  # thomasweise/texlive
  # adnrv/texlive
  LATEX_IMAGE: listx/texlive:2020

build_report:
  stage: build_report
  image: $LATEX_IMAGE
  script:
    - cd report
    - pdflatex report.tex
    - bibtex report.aux
    - pdflatex report.tex
    - pdflatex report.tex

  artifacts:
    paths:
      - "report/report.pdf"
